// src/components/ConfirmExit/ConfirmExit.tsx
import { Button } from '@mui/material';
import './ConfirmExit.scss';
import { useEffect } from 'react';

interface ConfirmExitProps {
  onClose: () => void;
}

export default function ConfirmExit({ onClose }: ConfirmExitProps) {
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        onClose();
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => {
      window.removeEventListener('keydown', handleKeyDown);
    };
  }, [onClose]);

  return (
    <div className="confirm-exit-overlay">
      <div className="confirm-exit">  
        <div className="confirm-exit-content">
          <p className='subtitle'>Are you sure you want to exit?</p>
          <div className="confirm-exit-buttons">
            <Button 
              className="btn-option" 
              variant="contained" 
              href='/'
              onClick={onClose}
            >
              Yes
            </Button>
            <Button 
              className="btn-option" 
              variant="outlined"
              onClick={onClose}
            >
              No
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}

// src/components/ConfirmExit/ConfirmExit.vue
<template>
  <div class="confirm-exit-overlay">
    <div class="confirm-exit">
      <div class="confirm-exit-content">
        <p class="subtitle">{{ $t('quit_dialog.title') }}</p>
        <div class="confirm-exit-buttons">
          <button class="btn-option" @click="$emit('confirm')">
            {{ $t('quit_dialog.back_to_menu') }}
          </button>
          <button class="btn-option" @click="$emit('cancel')">
            {{ $t('quit_dialog.cancel') }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import './ConfirmExit.scss';
</script>
